package com.codecool.termlib;

public enum TerminalCommands {
    COLOR_WHITE, COLOR_BLACK, HIDE_CURSOR, SHOW_CURSOR, SET_TERMINAL_DEFAULT, SET_TERMINAL_RAW, CLEAR_TERMINAL, SAVE_CURSOR_POSITION, RESTORE_CURSOR_POSITION
}