package com.codecool.termlib;

public enum TerminalCommands {
    COLOR_BG_WHITE, COLOR_BG_BLACK, COLOR_BG_DEFAULT, COLOR_FG_DEFAULT, HIDE_CURSOR, SHOW_CURSOR, SET_TERMINAL_DEFAULT, SET_TERMINAL_RAW, CLEAR_TERMINAL, SAVE_CURSOR_POSITION, RESTORE_CURSOR_POSITION
}